<?php
echo "<div class='content-table-wrapper'>
                            <table class='table'>
                                <thead class='thead-dark'>
                                    <tr>
                                        <th>Check box</th>
                                        <th>Id</th>
                                        <th>Username</th>
                                        <th>Email Id</th>
                                        <th>Mobile</th>
                                        <th>Active plan</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>1</td>
                                        <td>1JKOLOP</td>
                                        <td>sananthu47@gmail.com</td>
                                        <td>8884164717</td>
                                        <td>Year</td>
                                        <td>Live</td>
                                        <td>Delete</td>
                                    </tr>
                                </thead>
                            </table>
                        </div>";